### ISSUE TITLE
Morden: Transferring a 0 amount, results on a invalid transaction consuming all the gas

### ISSUE THREAD

**Issue by juanfranblanco** [nexusdev/dappsys#27]
Example:
http://testnet.etherscan.io/tx/0x7bac1f46c80fa65762e74c2da605642a1041b27f9e02838bc72a1a342dd54f5d

**Comment by juanfranblanco** [comment]
I guess this is the reason for this https://github.com/nexusdev/dappsys/blob/master/contracts/util/safety_test.sol

**Comment by nmushegian** [comment]
This has been on the backlog for a while, the fact that someone else caught it means I should hurry up =]

https://github.com/nexusdev/dappsys/tree/0.1.2-dev

**Comment by nmushegian** [comment]
FYI, the recommended usage of most tokens is via MakerUser, which included a patch to work around the problem

**Comment by juanfranblanco** [comment]
Yes, you mentioned I should create my own MakerUser for Nethereum.Maker 

Here I call the registry and get the token contract, what I will do is put a validator on the generic service for ERC20 and throw an exception if we are trying to transfer a 0 amount to avoid any gas costs regardless.

I know that you are throwing now, so it should not cost anything, but it will avoid invalid transactions.

**Comment by nmushegian** [comment]
again transferring 0 should not cause an exception, we are fixing this now, but a user library may as well stop you for simple transfers

**Comment by juanfranblanco** [comment]
ok

**Comment by nmushegian** [comment]
should be fixed throughout now

**Comment by juanfranblanco** [comment]
:+1:
