### ISSUE TITLE
git submodule add might need to be git submodule add -f

### ISSUE THREAD

**Issue by fikse** [nexusdev/dappsys#53]
The readme instructs me to run `git submodule add`, but for some reason i'm not able to do this without adding the `-f` flag. There is no `.gitignore` file in the project directory.

```
$ git init
Initialized empty Git repository in /Users/sjouke/myproject/.git/

$ dapple init

$ git submodule add https://github.com/nexusdev/dappsys .dapple/packages/dappsys

The following path is ignored by one of your .gitignore files:
.dapple/packages/dappsys
Use -f if you really want to add it.
```

**Comment by apmilen** [comment]
Updated. thanks for pointing that out. dapple creates a `.gitignore` file inside the `.dapple` directory. we will probably move it to the top level of your project directory in light of a separate issue, which would invalidate the need for `-f`. For now we will include it in the instructions though.
